### ISSUE TITLE
Necessity of CC switching

### ISSUE THREAD

**Issue by andkostov** [bluetiger9/USB-Type-C-Switch#1]
Hello!
I was curious about this circuit where you're carrying-over the CC from each source to the sink. I was wondering why you went for this approach, instead of plainly pulling down 5,1k on each side? I understand that you might want to keep the design bidirectional in case, but just wanted to confirm.
Thanks!

![image](https://github.com/bluetiger9/USB-Type-C-Switch/assets/58448051/932a7381-53dd-4150-b17f-88028f5a4fe3)

**Comment by bluetiger9** [comment]
Hi @andkostov! 🙂 The point of the CC switching is mainly to allow devices to be able negotiate higher USB PD power modes. With only pull-up resistors you would only get 5V with 500mA current limit.

In fact the point of the pull-up resistors here _(along with the mosfet-s)_ is to allow the board to power up when is connected to a proper USB Type-C source. Without those pull-us USB Type-C source does not usually provide power to the device.

**Comment by andkostov** [comment]
Thanks for the response @bluetiger9! I've been doing some reading and found TI's app note on the matter (SLYY109B: ['A Primer on USB Type-C® and USB Power Delivery Applications and Requirements'](https://www.ti.com/lit/wp/slyy109b/slyy109b.pdf)).

I've been giving it a read and can understand why you're controlling the gates (my understanding being that this is one way to implement CC logic without a PD controller, useful for non-USB 3.0 devices) - though my next question is how? I can see you have PU_CC_1/2 connected back to the microcontroller, but looking through the code I can't find any reference to analog pins 7, 10 or 11. Curious as to how the MOSFETs meant to be driven?

**Comment by attila-tokes** [comment]
Hi @andkostov. The switch does not implements USB PD logic in itself. The idea of the MOSFET-s is to have pull-down resistors that can be disabled. 🙂

Normally, the switch would start in an OFF state with no bridging between the ports. The `PU_CC` lines in this state would be high, enabling the pull-down resistors, thus allowing the switch to get power.

In the two ON states, the `PU_CC` of the currently active ports will be low, disabling the pull-downs. The CC lines are two ports are bridged together in this mode, thus enabling them to negotiate USB PD.

The project however is a bit of a work in progress, and source code is not updated yet. There was a mistake in the latest PCB run, and I didn't had the time to continue with the project.

**Comment by andkostov** [comment]
Hi @attila-tokes, thank you for the clarification! I understand that this design choice helps meet your reasonable cost requirement, instead of using a USB PD controller IC?

**Comment by attila-tokes** [comment]
@andkostov, the design is intended to work as a simple _"analog switch"_, allowing the connected devices use whatever USB Type-C feature they want. The reason for not to include USB PD controllers are both cost and complexity.

On the cost perspective the devices does not needs more than 5V, so adding a USB PD controller would add no benefit.

On the complexity side, using PD controllers will likely mess up PD communication between the two connected devices. That means we would need to drop the analog switch, and implement PD protocol translation between the connected devices, which would be a nightmare.

**Comment by andkostov** [comment]
@bluetiger9 thank you for your time & explanations; they have been very helpful! I understand your reasoning for the CC switching circuit, as opposed to [opening up 5V 3A by default](https://forum.digikey.com/t/simple-way-to-use-usb-type-c-to-get-5v-at-up-to-3a-15w/7016) in case of under-powered source / DFP ports.
